<link rel="stylesheet" type="text/css" href="../css/admin.css" />
<link rel="stylesheet" type="text/css" href="../css/jqueryslidemenu.css" />
<link rel="stylesheet" type="text/css" href="../lib/jquery/css/ui-lightness/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="../lib/jquery/css/ui-lightness/jquery-ui-1.8.custom.css" />

<!--Google Maps API-->
<!--<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />-->
<!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>-->

<!--<script type="text/javascript" language="javascript" src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=ABQIAAAAxpTKzG0WIYsWE5g8NjroyxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxThC3IqN-Fln37vajPnxvxzw80Iiw"></script>-->
<script type="text/javascript" language="javascript" src="http://www.google.com/jsapi?key=ABQIAAAAxpTKzG0WIYsWE5g8NjroyxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxThC3IqN-Fln37vajPnxvxzw80Iiw"></script>
<!-- voor als er geen internet is de onderstaande scripts uncommenten en het script hier boven in comments zetten-->
<!--<script type="text/javascript" language="javascript" src="../lib/jquery/js/jquery-1.3.2.js"></script>-->
<!--<script type="text/javascript" language="javascript" src="../lib/jquery/js/jquery-ui-1.8.custom.min.js"></script>-->

<script type="text/javascript" language="javascript" src="../scripts/load_frameworks.js"></script>
<script type="text/javascript" language="javascript" src="../lib/jquery/plugins/jquery.maskedinput.js"></script>