<!-- stylesheetssss -->
		<link rel="stylesheet" href="css/reset.css" type="text/css" media="screen" charset="utf-8" />
		<!-- temp colorscheme -->
<!--		<link rel="stylesheet" href="css/text.css" type="text/css" media="screen" charset="utf-8" />-->
		<link rel="stylesheet" href="css/jquery.clockpick.1.2.7.css" type="text/css" media="screen" charset="utf-8" />
		<link rel="stylesheet" href="lib/jquery/css/ui-lightness/jquery-ui.css" type="text/css" media="all" />

		<!-- javascript libraries -->

		<!--Google Maps API-->
<!--		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />-->
<!--		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>-->

		<!-- ABQIAAAAxpTKzG0WIYsWE5g8NjroyxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxThC3IqN-Fln37vajPnxvxzw80Iiw -->
<!--		<script type="text/javascript" language="javascript" src="lib/phpjs/php.full.min.js"></script>-->
<!--		<script type="text/javascript" language="javascript" src="http://www.google.com/jsapi?key=ABQIAAAAxpTKzG0WIYsWE5g8NjroyxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxThC3IqN-Fln37vajPnxvxzw80Iiw"></script>-->
<!-- voor als er geen internet is de onderstaande scripts uncommenten en het script hier boven in comments zetten-->
		<script type="text/javascript" language="javascript" src="lib/jquery/js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" language="javascript" src="lib/jquery/js/jquery-ui-1.8.custom.min.js"></script>

		<script type="text/javascript" language="javascript" src="scripts/load_frameworks.js"></script>

		<script type="text/javascript" language="javascript" src="lib/jquery/plugins/jquery-ui-timepicker-addon-0.5.js"></script>
<!--		<script type="text/javascript" language="javascript" src="lib/jquery/plugins/jquery.clockpick.1.2.7.js"></script>-->
		<script type="text/javascript" language="javascript" src="lib/jquery/locale/jquery.ui.datepicker-nl.js"></script>
		<script type="text/javascript" language="javascript" src="lib/jquery/plugins/jquery.cookie.js"></script>
<!--		<script type="text/javascript" language="javascript" src="lib/jquery/plugins/jquery.easing.1.3.js"></script>-->
		<script type="text/javascript" language="javascript" src="scripts/tardis.js"></script>
		<script type="text/javascript" language="javascript" src="scripts/tmap.js"></script>